# Generated by Django 4.2 on 2024-03-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_rename_start_datetime_reservation_start_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='acsess',
            field=models.BooleanField(default=True),
        ),
    ]
