# Generated by Django 4.2 on 2024-03-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessions',
            options={'ordering': ['date', 'start_time']},
        ),
        migrations.AlterField(
            model_name='meetingroom',
            name='room_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
