# Generated by Django 4.2 on 2024-03-12 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_sessions_options_alter_meetingroom_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='name',
            field=models.CharField(default='session', max_length=30),
        ),
    ]
