# Generated by Django 4.2 on 2024-03-15 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_merge_20240314_2105'),
        ('rooms', '0006_alter_meetingroom_company_team_alter_sessions_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='manager',
        ),
        migrations.AlterField(
            model_name='meetingroom',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_rooms', to='company.company'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='rooms.company'),
        ),
    ]
