# Generated by Django 4.2 on 2024-03-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_companymanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='CompanyManager',
            field=models.CharField(blank=True, choices=[('Company CEO', 'Company CEO'), ('Member', 'member')], default='Member', max_length=15),
        ),
    ]
