# Generated by Django 4.2 on 2024-03-14 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_name_alter_team_name'),
        ('company', '0002_alter_team_name'),
    ]

    operations = [
    ]
